import { useCallback, useEffect, useState } from 'react';
import { Alert, Pressable, Text, View } from 'react-native';

import { AppButton, AppInput, AppModal } from '@/components/ui';
import { claimBonusCampaign, fetchAvailableBonusCampaigns } from '@/features/bonus-campaigns/bonus-campaign-api';
import type { AvailableBonusCampaign } from '@/features/bonus-campaigns/types';
import { fetchAvailableFeaturePoll, submitFeaturePollVote } from '@/features/feature-polls/feature-poll-api';
import type { AvailableFeaturePoll } from '@/features/feature-polls/types';
import { useAppTheme } from '@/hooks/use-app-theme';
import { useAuth } from '@/providers/auth-provider';
import { useNetwork } from '@/providers/network-provider';

const OTHER = '__other__';

export function EngagementSurfaces() {
  const { user, profile, refreshProfile } = useAuth(); const { canPerformWrites } = useNetwork();
  const { tokens } = useAppTheme();
  const [campaign, setCampaign] = useState<AvailableBonusCampaign | null>(null); const [bonusOpen, setBonusOpen] = useState(false);
  const [poll, setPoll] = useState<AvailableFeaturePoll | null>(null); const [selected, setSelected] = useState(''); const [other, setOther] = useState(''); const [loading, setLoading] = useState(false);
  const load = useCallback(async () => { if (!user || !profile) return; const [campaigns, availablePoll] = await Promise.all([fetchAvailableBonusCampaigns().catch(() => []), fetchAvailableFeaturePoll().catch(() => null)]); setCampaign(campaigns[0] ?? null); setBonusOpen(Boolean(campaigns[0]) && !availablePoll); setPoll(availablePoll); }, [profile, user]);
  useEffect(() => { void load(); }, [load]);
  const claim = async () => { if (!campaign) return; if (!canPerformWrites) { Alert.alert('Brak internetu', 'Bonusu nie można odebrać offline.'); return; } setLoading(true); try { const result = await claimBonusCampaign(campaign.id); await refreshProfile(); setCampaign(null); setBonusOpen(false); Alert.alert('Bonus odebrany', `Dodano ${Number(result.amount).toFixed(2)} zł. Nowe saldo: ${Number(result.balance_after).toFixed(2)} zł.`); } catch { Alert.alert('Bonus', 'Nie udało się odebrać bonusu. Spróbuj ponownie.'); } finally { setLoading(false); } };
  const vote = async () => { if (!poll || !selected) { Alert.alert('Wybierz odpowiedź'); return; } if (selected === OTHER && !other.trim()) { Alert.alert('Wpisz swoją propozycję'); return; } if (!canPerformWrites) { Alert.alert('Brak internetu', 'Głos nie będzie kolejkowany offline.'); return; } setLoading(true); try { await submitFeaturePollVote({ pollId: poll.id, optionId: selected === OTHER ? null : selected, otherText: selected === OTHER ? other.trim() : null }); setPoll(null); setSelected(''); setOther(''); if (campaign) setBonusOpen(true); } catch { Alert.alert('Głosowanie', 'Nie udało się zapisać głosu. Spróbuj ponownie.'); } finally { setLoading(false); } };
  return <>
    {campaign && !bonusOpen && !poll && <Pressable accessibilityRole="button" onPress={() => setBonusOpen(true)} style={{ position: 'absolute', right: 16, bottom: 96, zIndex: 80, minHeight: 48, borderRadius: 24, justifyContent: 'center', backgroundColor: '#ff0a54', paddingHorizontal: 18, shadowColor: '#000', shadowOpacity: 0.3, shadowRadius: 12 }}><Text style={{ color: '#fff', fontWeight: '900' }}>🎁 Odbierz bonus</Text></Pressable>}
    {campaign && <AppModal visible={bonusOpen} title="Bonus dla Ciebie" onClose={() => setBonusOpen(false)} presentation="center"><View style={{ alignItems: 'center', gap: 14 }}><Text style={{ fontSize: 44 }}>✨</Text><Text style={{ color: tokens.colors.foreground, fontSize: 24, fontWeight: '900', textAlign: 'center' }}>{campaign.title}</Text><Text style={{ color: tokens.colors.mutedForeground, textAlign: 'center' }}>{campaign.description}</Text><Text style={{ color: tokens.colors.primary, fontSize: 42, fontWeight: '900' }}>{Number(campaign.amount).toFixed(2)} zł</Text><AppButton loading={loading} disabled={!canPerformWrites} onPress={() => void claim()} fullWidth>{canPerformWrites ? 'Odbierz bonus' : 'Brak internetu'}</AppButton><AppButton variant="ghost" disabled={loading} onPress={() => setBonusOpen(false)} fullWidth>Później</AppButton></View></AppModal>}
    {poll && <AppModal visible title={poll.title_enabled === false ? 'Głosowanie' : poll.title || 'Głosowanie'} onClose={() => undefined} presentation="center"><View style={{ gap: 12 }}>{poll.description_enabled !== false && poll.description && <Text style={{ color: tokens.colors.mutedForeground }}>{poll.description}</Text>}{poll.question_enabled !== false && <Text style={{ color: tokens.colors.foreground, fontSize: 18, fontWeight: '900' }}>{poll.question}</Text>}{poll.options.map(option => <Pressable key={option.id} onPress={() => setSelected(option.id)} style={{ minHeight: 48, justifyContent: 'center', borderWidth: 2, borderColor: selected === option.id ? tokens.colors.primary : tokens.colors.border, borderRadius: 12, backgroundColor: tokens.colors.backgroundElevated, paddingHorizontal: 14 }}><Text style={{ color: tokens.colors.foreground, fontWeight: '700' }}>{selected === option.id ? '● ' : '○ '}{option.label}</Text></Pressable>)}{poll.allow_other && <Pressable onPress={() => setSelected(OTHER)} style={{ minHeight: 48, justifyContent: 'center', borderWidth: 2, borderColor: selected === OTHER ? tokens.colors.primary : tokens.colors.border, borderRadius: 12, backgroundColor: tokens.colors.backgroundElevated, paddingHorizontal: 14 }}><Text style={{ color: tokens.colors.foreground, fontWeight: '700' }}>{selected === OTHER ? '● ' : '○ '}Inne</Text></Pressable>}{selected === OTHER && <AppInput label="Twoja propozycja" value={other} onChangeText={setOther} multiline />}<AppButton loading={loading} disabled={!selected || !canPerformWrites} onPress={() => void vote()}>{canPerformWrites ? 'Oddaj głos' : 'Brak internetu'}</AppButton></View></AppModal>}
  </>;
}
