/* eslint-disable @typescript-eslint/no-require-imports -- Metro resolves bundled image assets through static require calls. */
import { useCallback, useEffect, useState } from 'react';
import { Alert, ImageBackground, ScrollView, Text, View } from 'react-native';

import { AppAvatar, AppButton, AppCard } from '@/components/ui';
import { claimDailyJackpotReward, getDailyJackpotDraw, revealDailyJackpotDraw } from '@/features/jackpot/api/jackpot';
import { formatJackpotAmount } from '@/features/jackpot/lib/jackpotFormat';
import { useAuth } from '@/providers/auth-provider';
import type { DailyJackpotDraw } from '@/features/jackpot/types';

export function JackpotDrawScreen({ roundId }: { roundId: string }) {
  const { refreshProfile, updateProfileBalance } = useAuth(); const [draw, setDraw] = useState<DailyJackpotDraw | null>(null); const [loading, setLoading] = useState(true); const [revealing, setRevealing] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { setDraw(await getDailyJackpotDraw(roundId)); } catch (cause) { Alert.alert('Jackpot', cause instanceof Error ? cause.message : 'Nie znaleziono losowania.'); } finally { setLoading(false); } }, [roundId]);
  useEffect(() => { void load(); }, [load]);
  const reveal = async () => { setRevealing(true); try { setDraw(await revealDailyJackpotDraw(roundId)); } catch (cause) { Alert.alert('Losowanie', cause instanceof Error ? cause.message : 'Nie udało się odsłonić wyniku.'); } finally { setRevealing(false); } };
  const claim = async () => { setRevealing(true); try { const result = await claimDailyJackpotReward(roundId); updateProfileBalance(result.balanceAfter); await refreshProfile(); setDraw(await getDailyJackpotDraw(roundId)); Alert.alert('Gratulacje!', `Odebrano ${formatJackpotAmount(result.amount)}.`); } catch (cause) { Alert.alert('Nagroda', cause instanceof Error ? cause.message : 'Nie udało się odebrać nagrody.'); } finally { setRevealing(false); } };
  if (loading || !draw) return <View style={{ flex: 1, backgroundColor: '#090005', alignItems: 'center', justifyContent: 'center' }}><Text style={{ color: '#d9a8b6' }}>Przygotowujemy losowanie…</Text></View>;
  const resultVisible = Boolean(draw.resultViewedAt || draw.winningTicketNumber !== null);
  return <ImageBackground source={require('../../../../assets/images/jackpot/jackpot-bg.webp')} style={{ flex: 1, backgroundColor: '#12051b' }} imageStyle={{ opacity: 0.42 }}><ScrollView contentContainerStyle={{ padding: 14, paddingBottom: 40, gap: 14 }}><View style={{ alignItems: 'center', gap: 7, paddingVertical: 24 }}><Text style={{ color: '#f6c642', fontSize: 12, letterSpacing: 3, fontWeight: '900' }}>DAILY JACKPOT</Text><Text style={{ color: '#fff', fontSize: 38, fontWeight: '900' }}>{formatJackpotAmount(draw.prizeAmount)}</Text><Text style={{ color: '#d9cce0' }}>{new Date(draw.poolDate).toLocaleDateString('pl-PL')} · {draw.ticketCount} ticketów</Text></View><AppCard style={{ backgroundColor: '#1e1028ee', borderColor: '#f6c64266', alignItems: 'center', gap: 14, padding: 24 }}><Text style={{ color: '#d9cce0', fontWeight: '800' }}>{resultVisible ? 'WYLOSOWANY TICKET' : 'WYNIK CZEKA'}</Text><View style={{ width: 140, height: 140, borderRadius: 70, borderWidth: 6, borderColor: '#f6c642', backgroundColor: '#4d174d', alignItems: 'center', justifyContent: 'center' }}><Text style={{ color: '#fff', fontSize: 50, fontWeight: '900' }}>{resultVisible && draw.winningTicketNumber !== null ? `#${String(draw.winningTicketNumber).padStart(2, '0')}` : '?'}</Text></View>{!resultVisible && <AppButton loading={revealing} onPress={() => void reveal()}>Odsłoń wynik</AppButton>}{resultVisible && draw.winnerUsername && <View style={{ alignItems: 'center', gap: 7 }}><AppAvatar name={draw.winnerUsername} source={draw.winnerAvatarUrl ? { uri: draw.winnerAvatarUrl } : undefined} size={52} /><Text style={{ color: '#fff', fontSize: 22, fontWeight: '900' }}>{draw.winnerUsername}</Text></View>}{draw.currentUserIsWinner && draw.rewardCreditStatus === 'pending' && <AppButton loading={revealing} onPress={() => void claim()}>Odbierz {formatJackpotAmount(draw.prizeAmount)}</AppButton>}{draw.status === 'rolled_over' && <Text style={{ color: '#f6c642', textAlign: 'center' }}>Za mało unikalnych graczy — pula przechodzi na kolejne losowanie.</Text>}</AppCard><AppCard style={{ backgroundColor: '#1e1028ee', borderColor: '#ffffff22', gap: 10 }}><Text style={{ color: '#fff', fontSize: 18, fontWeight: '900' }}>Uczestnicy</Text>{draw.participants.map(player => <View key={player.userId} style={{ flexDirection: 'row', justifyContent: 'space-between' }}><Text style={{ color: '#fff' }}>{player.username}</Text><Text style={{ color: '#d9cce0' }}>{player.ticketNumbers.map(number => `#${String(number).padStart(2, '0')}`).join(' ')}</Text></View>)}</AppCard></ScrollView></ImageBackground>;
}
